<?php
$host="db.cecs.pdx.edu";                                                                                           
$user="schedule";                                                                                                 
$password="jm)n3Ffz6m";

$db_host="db.cecs.pdx.edu";                                                                               
$db_user="schedule";                                                                                    
$db_password="jm)n3Ffz6m";
?>
